export const mutators = {
  ADD_ERROR: "ADD_ERROR",
  REMOVE_ERROR: "REMOVE_ERROR",
  TOGGLE_SINGLE_TOAST: "TOGGLE_SINGLE_TOAST"
};

export const actors = {
  ADD_TOAST: "ADD_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST",
  SHOW_SINGLE_TOAST: "SHOW_SINGLE_TOAST",
  HIDE_SINGLE_TOAST: "HIDE_SINGLE_TOAST"
};
